#!/usr/bin/env bash
# print " best school" 10 times with while loop.
# "Hi" before best school on the 9th

c=0

while [ $c -lt 10 ]
do
  if [ $c -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( c++))
done
