#!/usr/bin/env bash
# loop from 1 to 10 and display:
#   "bad luck" for the 4th line
#   "good luck" 8th line
#   "Best School" for all other lines

c=0

while [ $c -lt 10 ]
do
  if [ $c -eq 3 ]
  then
    echo "bad luck"
  elif [ $c -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School'
  fi
  (( c++))
done
